# These are all the cops that are disabled in the default configuration.

Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false

Encoding:
  Description: 'Use UTF-8 as the source file encoding.'
  Enabled: false
